version: "3"

services:
  frontend:
    env_file:
      - .env
    build: ./frontend
    expose:
      - ${NUXT_PORT}
    ports:
      - ${NUXT_PORT}:${NUXT_PORT}
    depends_on:
      - backend
    links:
      - backend
    volumes:
    - ./frontend:/usr/src
    command: npm run start-dev
  backend:
    env_file:
      - .env
    build: ./backend
    expose:
      - ${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./backend:/usr/src
    command: npm run start-dev
