version: "3"

services:
  frontend:
    env_file:
      - .env
    build: ./frontend
    depends_on:
      - backend
      - nginx
    volumes:
    - ./frontend:/usr/src
    restart: always
    command: npm run start-dev
  backend:
    env_file:
      - .env
    build: ./backend
    volumes:
      - ./backend:/usr/src
    restart: always
    depends_on:
      - websocket
      - nginx
    command: npm run start-dev
  websocket:
    env_file:
      - .env
    build: ./websocket
    volumes:
      - ./websocket:/usr/src
    depends_on:
      - nginx
    restart: always
    command: npm run start-dev
  nginx:
    env_file:
      - .env
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/:/etc/nginx
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
