### Register
POST http://localhost:3030/api/auth/register
Content-Type: application/json

{
  "username": "Jack",
  "password": "super-mega-secret",
  "email": "jack@github.com"
}

### Login
POST http://localhost:3030/api/auth/login
Content-Type: application/json

{
  "password": "super-mega-secret",
  "email": "jack@github.com"
}
